<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0-windows</TargetFramework><Version>1.2.4</Version><AssemblyName>AnimeVEUpdater</AssemblyName><Product>AnimeVE</Product><Title>AnimeVE Component Tool</Title><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><EnableDefaultCompileItems>false</EnableDefaultCompileItems><PublishSingleFile>false</PublishSingleFile><SelfContained>true</SelfContained><RuntimeIdentifier>win-x64</RuntimeIdentifier></PropertyGroup><ItemGroup><Compile Include="Updater.cs"/><PackageReference Include="System.Management" Version="10.0.0"/></ItemGroup></Project>
