using AnimeJaNaiConfEditor.ViewModels;
using AnimeJaNaiConfEditor.Views;
using Avalonia;
using Avalonia.Headless;
using Avalonia.LogicalTree;
using Avalonia.Controls;
using ReactiveUI.Avalonia;
var fixture=Path.GetFullPath(args[0]);Directory.CreateDirectory(fixture);
Directory.CreateDirectory(Path.Combine(fixture,"onnx"));Directory.CreateDirectory(Path.Combine(fixture,"rife"));
Environment.SetEnvironmentVariable("ANIMEJANAI_DATA_DIR",fixture);
Environment.SetEnvironmentVariable("ANIMEJANAI_ROOT",fixture);
File.Copy("animejanai/animejanai.conf",Path.Combine(fixture,"animejanai.conf"),true);
void Check(bool valid,string label){if(!valid)throw new Exception(label);Console.WriteLine("PASS "+label);}
AppBuilder.Configure<AnimeJaNaiConfEditor.App>().UseHeadless(new AvaloniaHeadlessPlatformOptions()).UseReactiveUI(_=>{}).SetupWithoutStarting();
var vm=new MainWindowViewModel();
Check(typeof(MainWindowViewModel).GetProperty("DefaultUpscaleSlots")==null && typeof(MainWindowViewModel).GetMethod("HandleShowDefaultProfile")==null,"builtin preset model and actions removed");
foreach(var key in new[]{"QualitySharp","BalancedSharp","PerformanceSharp"})Check(typeof(AnimeJaNaiConf).GetProperty(key)==null,"obsolete preset field removed: "+key);
Check(vm.AnimeJaNaiConf.UpscaleSlots.Count==9 && vm.CommonResolutions.Length>0,"custom profiles and resolution choices preserved");
var names=vm.AnimeJaNaiConf.UpscaleSlots.Select(s=>s.ProfileName).ToArray();
var window=new MainWindow {DataContext=vm};
window.Measure(new Size(1100,800));window.Arrange(new Rect(0,0,1100,800));
Check(names.SequenceEqual(vm.AnimeJaNaiConf.UpscaleSlots.Select(s=>s.ProfileName)),"constructing the view preserves custom profile names");
vm.HandleShowCustomProfile("2");vm.SelectDefaultProfile();
Check(typeof(MainWindowViewModel).GetMethod("LaunchBenchmark")==null,"builtin preset benchmark action removed");
Check(vm.AnimeJaNaiConf.DefaultSlot==2,"custom profile can be selected as startup default");
vm.WriteAnimeJaNaiConf();
var saved=File.ReadAllText(Path.Combine(fixture,"animejanai.conf"));
Check(!saved.Contains("quality_preset") && !saved.Contains("balanced_preset") && !saved.Contains("performance_preset"),"manager writes only supported profile configuration");
Console.WriteLine("PASS manager profile checks without desktop interaction");
