using AnimeJaNaiConfEditor.ViewModels;
using AnimeJaNaiConfEditor.Views;
using Avalonia;
using Avalonia.Headless;
using Avalonia.LogicalTree;
using Avalonia.Controls;
using ReactiveUI.Avalonia;
if(args.Length!=1){Console.Error.WriteLine("Usage: ManagerProfiles <empty fixture directory>");Environment.ExitCode=2;return;}
var fixture=Path.GetFullPath(args[0]);Directory.CreateDirectory(fixture);
Directory.CreateDirectory(Path.Combine(fixture,"onnx"));Directory.CreateDirectory(Path.Combine(fixture,"rife"));
Environment.SetEnvironmentVariable("ANIMEJANAI_DATA_DIR",fixture);
Environment.SetEnvironmentVariable("ANIMEJANAI_ROOT",fixture);
File.Copy("animejanai/animejanai.conf",Path.Combine(fixture,"animejanai.conf"),true);
void Check(bool valid,string label){if(!valid)throw new Exception(label);Console.WriteLine("PASS "+label);}
AppBuilder.Configure<AnimeJaNaiConfEditor.App>().UseHeadless(new AvaloniaHeadlessPlatformOptions()).UseReactiveUI(_=>{}).SetupWithoutStarting();
Directory.Delete(Path.Combine(fixture,"onnx"));
Directory.Delete(Path.Combine(fixture,"rife"));
var vm=new MainWindowViewModel();
Check(vm.GetAllModels().Count==0,"manager supports a fresh install without model directories");
Check(typeof(MainWindowViewModel).GetProperty("DefaultUpscaleSlots")==null && typeof(MainWindowViewModel).GetMethod("HandleShowDefaultProfile")==null,"builtin preset model and actions removed");
foreach(var key in new[]{"QualitySharp","BalancedSharp","PerformanceSharp"})Check(typeof(AnimeJaNaiConf).GetProperty(key)==null,"obsolete preset field removed: "+key);
Check(vm.AnimeJaNaiConf.UpscaleSlots.Count==9 && vm.CommonResolutions.Length>0,"custom profiles and resolution choices preserved");
var names=vm.AnimeJaNaiConf.UpscaleSlots.Select(s=>s.ProfileName).ToArray();
var window=new MainWindow {DataContext=vm};
window.Measure(new Size(1100,800));window.Arrange(new Rect(0,0,1100,800));
Check(window.GetLogicalDescendants().OfType<TabItem>().Count()==3,"About is the third manager tab");
var picker=vm.ComponentManager;
picker.Packs.Add(new ComponentItem{Name="optional",Recommended=true});
picker.Packs.Add(new ComponentItem{Name="installed",Installed=true,Selected=true});
picker.SelectRecommended();Check(picker.Packs.All(p=>p.Selected),"recommended selection preserves installed components");
picker.ClearSelection();Check(!picker.Packs[0].Selected && picker.Packs[1].Selected,"reset selection preserves installed components");
Directory.CreateDirectory(Path.Combine(fixture,"onnx"));
File.WriteAllText(Path.Combine(fixture,"onnx","new-model.onnx"),"fixture");
vm.RefreshComponentAwareness();
Check(vm.AnimeJaNaiConf.UpscaleSlots.SelectMany(s=>s.Chains).SelectMany(c=>c.Models).All(m=>m.AllModels.Contains("new-model")),"downloaded models refresh existing profile pickers");
Check(names.SequenceEqual(vm.AnimeJaNaiConf.UpscaleSlots.Select(s=>s.ProfileName)),"constructing the view preserves custom profile names");
vm.HandleShowCustomProfile("2");vm.SelectDefaultProfile();
Check(typeof(MainWindowViewModel).GetMethod("LaunchBenchmark")==null,"builtin preset benchmark action removed");
Check(vm.AnimeJaNaiConf.DefaultSlot==2,"custom profile can be selected as startup default");
vm.WriteAnimeJaNaiConf();
var saved=File.ReadAllText(Path.Combine(fixture,"animejanai.conf"));
Check(!saved.Contains("quality_preset") && !saved.Contains("balanced_preset") && !saved.Contains("performance_preset"),"manager writes only supported profile configuration");
Console.WriteLine("PASS manager profile checks without desktop interaction");
